#!/bin/sh
function deactivate() {
  if [ -n "$GOENVNAME" ]; then
    unset GOENVNAME
  fi

  if [ -n "$_OLD_GOROOT" ]; then
    export GOROOT="$_OLD_GOROOT"
    unset _OLD_GOROOT
  fi

  if [ -n "$_OLD_PS1" ]; then
    export PS1="$_OLD_PS1"
    unset _OLD_PS1
  fi

  if [ -n "$_OLD_PATH" ]; then
    export PATH="$_OLD_PATH"
    unset _OLD_PATH
  fi

  if [ -n "$_OLD_GOPATH" ]; then
    export GOPATH="$_OLD_GOPATH"
    unset _OLD_GOPATH
  fi

  if [ "$1" != "init" ]; then
    unset -f deactivate
  fi
}

deactivate init

export _OLD_PATH="$PATH"
export _OLD_GOPATH="$GOPATH"
export _OLD_GOROOT="$GOROOT"
export _OLD_PS1="$PS1"
export GOENVNAME="revel"
export PS1="(go:revel) $_OLD_PS1"
export GOPATH=/Users/furukawa.yosuke/Program/revel
export PATH="$GOPATH/bin":$PATH

